### ISSUE TITLE
Client Pooling Issue and max connections to postresql database

### ISSUE THREAD

**Issue by bmershon** [bmershon/wikiblocks-search#1]
### EDIT: Figured out part of the problem

Bigger instance with more memory yields more max connections. Amazon sets max_connections as a function of memory.

For example, my current m4.large instance gives 259 connections.

### EDIT 2 with solution outline:

From my conversation with vitaly-t:

**I asked:**

>I am a little confused about how I might use your detached and shared connections to satisfy the following use case:

>There are a maximum number of connections that my database can handle. Call this number M.

>A typical request results in a search which needs to make between 5 and 40 queries to the database. Let's say this is 40 queries in the worst case. Call this number Q.

>I'd like to maintain a concurrency level R, which is the number of current in-progress searches that I can perform.

>100 in-progress searches (requests) could use up R x Q = 100 x 40 = 400 < M connections to the database.

>This is in contrast to my current search pipeline which uses a single connection for all queries related to a search. In this slower case, 100 requests produces 100 connections to the database. I call this the one-tier client pooling method.

>It seems like there needs to be a pool (or queue like Mike Bostock's queue-async) which manages the number of concurrent requests, and each request should itself have a small pool of clients to use up for the 40 or so queries that a typical search might execute in parallel.

>I was hoping you might weigh in on this two-tier approach to pooling. Again, the second tier is an effort to allow an in-progress search to send its queries in parallel, rather than waiting for 40 or so queries to go one-at-a-time through a single connection. In a sense, the size of the first "pool" is R, and the size of each pool allocated to an in-progress search is Q.

>Of course, the limit M inherent to the database must be respected at all times:

>R x Q < M

**Vitaly-t responded with a solution that uses his pg-promise library:**

>So here's my best advise on getting started.

>Wrap those 5-40 queries into a task.
If the task makes changes to the database, execute it as a transaction: db.tx
If the task does only read-only operations, execute it as a task: db.task.
For easy analysis and understanding how everything works:

>Tag all of your tasks and transactions (name them): db.task("myTask", cb), db.tx("myTX", cb)
Use pg-monitor from the very beginning, to see how everything is executing against the database. Here's complete example.
Once you get there, it will be easier to see how to proceed ;)

>UPDATE: Don't let those detached and shared connections take you off course. They are low-level considerations designed earlier. Tasks is a higher-level approach, which should be used.

>And the entire library was built on top of a connection pool, so you get that automatically. Also you can tweak it as shown earlier.

**Comment by manaj999** [comment]
Nice work, Brooks. That would've been a massive issue for us in production. Will look into tools or practices for managing client pools tomorrow unless you already have some leads/thoughts.

**Comment by bmershon** [comment]
See #4, which covers the use of pg-promise. I've been talking to the author of that library. Here's the comment thread if you wanna read my setup and his answer. I've yet to look much further, but if we are using PSQL, pg-promise does indeed seem to be the most solid solution.

https://github.com/vitaly-t/pg-core/issues/1#issuecomment-157135197

**Comment by bmershon** [comment]
The best way to get started using pg-promise is probably to write small tests for operations before attempting to use them in a complex search process. I'd personally like to become familiar with the [Tape library](https://github.com/substack/tape), so that's the way I'll proceed and I encourage others to jump onboard with using Tape.

Basically, write tests and play around until tests pass. Once you know each of the types of queries we perform works, we can assemble them into the search pipeline just they way I currently do. Notice that I stuffed all of the query functions in a *queries.js* file.
