### ISSUE TITLE
using pg-promise

### ISSUE THREAD

**Issue by bmershon** [bmershon/wikiblocks-search#4]
Considering using [pg-promise](https://github.com/vitaly-t/pg-promise#about), which is built on top of node-postgres (pg).

Here's the primer: https://github.com/vitaly-t/pg-promise/wiki/Why-use-it%3F

Still reviewing the docs to see if it will help solve the need for connection pooling and transactions in a better way than pg currently does.

**Comment by markbotros** [comment]
I'm reading the docs - seems like promise chaining was introduced to solve similar issues. I can't tell if it's a scalable solution. I think testing on a larger db server will be interesting and will tell us if it's a server-side issue.
