### ISSUE TITLE
Using generators to make search more parallel

### ISSUE THREAD

**Issue by bmershon** [bmershon/wikiblocks-search#6]
All of the "hooks" or arrays of tokens that came from a single String on the Wikipedia article can be used to form a query that executes independently of the other "hooks" and their corresponding queries.

For example, ["hilbert", "curve"] is a hook that can be used to search for all gists with *any* of these two tags. A generator function's job is to expose a next() method that gives the next "best" match for these terms. There are only two terms, but we might want to get matches on both tags before we consider serving up results which match on only "curve." 

Moreover, we might take into consideration the rarity or specificity of the term relative to the database of tags. "hilbert" might be a more specific tag, and this would cause us to promote matches on "hilber" over matches on "curve."

The next() method currently returns a Promise object which supports all of the functionality Bluebird's implementation exposes: http://bluebirdjs.com/docs/api/new-promise.html

Here's some a rough idea of how the generator might be used:

*iterating through all matches on a set of tags*
```js
    var it = db.tagged(tags);

    it.next().then(function lambda(result) {
        if(result.done) {
            test.end();
            pgp.end();
            return;
        } else {
            test.ok(result.value.tags.length, "gist with " + result.value.tags);
            it.next().then(lambda);
        }
    });

```

A portion of the *generator constructor*

```js

    function next() {
        if(ready)
            return new Promise(function(resolve) {
                resolve((ready.length) ? {value: ready.shift(), done: false} : {done: true});
            });
        else 
            return fetch().then(next);
    }
```

## TODO

- care must be taken not to return too many results from a fetch query at any given time, because these are stored in memory
- sort current batch of *ready* results. This is the array of gists from which next() either takes the first entry or populates with an asynchronous database query
- create a pipeline which draws the best k results from a queue of generators, all of which support the next() functionality. Weight results in adding to a "master list" by a score property on the returned gist, as well as by a weight given to the generator itself. This latter weight reflects the relevance of the different types of hooks (title, aliases, categories, see also, ...).
- manage the size of the client pools available for search, since this approach opens up many connections per "search". This comes at the expense of the number of concurrent searches, but does help speed up each individual search.

**Comment by markbotros** [comment]
Much of this implementation is over my head but I think the core issue of parallelization here is a good problem to address. Are we thinking of allocating connections dynamically? Might be cool to load-ration based on traffic.

**Comment by markbotros** [comment]
Damn sorry I accidentally closed this. Back to the tutorials.
